language: python
python:
  - "3.7"
before_install:
install:
  - pip install -r requirements.txt
before_script: 
script:
  - ./pytest 
after_success:
  - "./ci/deploy"
after_failure:
deploy:
  provider: lambda
  function_name: "thedasbot-prod-trigger"
  region: "us-east-1"
  role: "arn:aws:iam::054995062387:role/thedasbot-prod-us-east-1-lambdaRole"
  runtime: "python3.7"
  module_name: "handler"
  handler_name: "trigger"
  on:
    branch: master
